# Generated by Django 5.1.5 on 2025-04-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_role_testuser_user_product_message_followed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
    ]
