# Generated by Django 5.1.5 on 2025-05-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_user_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='product_owner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
