# Generated by Django 5.1.5 on 2025-05-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_owner_product_product_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUser',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_password',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='login',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
