# Generated by Django 5.1.5 on 2025-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_testuser_remove_client_user_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.TextField(default=''),
        ),
    ]
